name: Trigger merge test1 on a CRON schedule

on:
  workflow_dispatch:
  schedule:
    # At 11am and 4pm from Monday through Friday.
    - cron: '0 11,16 * * 1-5'

env:
  GIT_USERNAME: tuyenphann
  GIT_EMAIL: tuyenphan@kms-technology.com

  REPO: https://tuyenphann:${{secrets.GITHUB_TOKEN}}@github.com/tuyenphann/circle-ci-demo.git
  REPO_NAME: circle-ci-demo
  ORIGIN: https://github.com/tuyenphann/circle-ci-demo.git

  CURRENT_BRANCH: local/test1
  BRANCHES: |
    - main
    - test2

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Merge multiple branches into current branch
      run: |
        echo "🔥 Cloning from ${{env.REPO_NAME}}"
        git clone ${{env.REPO}} -b ${{env.CURRENT_BRANCH}}
        CLONE_CMD_STATUS=$?

        if [ ! -d "${{env.REPO_NAME}}" ]
        then
          echo "⛔️ Error detected while cloning ${{env.REPO_NAME}}"
          exit 1
        fi
        echo ""

        cd ${{env.REPO_NAME}}
        git config user.name "${{GIT_USERNAME}}"
        git config user.email "${{GIT_EMAIL}}"

        for BRANCH in ${{env.BRANCHES}}
        do
          echo "🔥 Pulling from $BRANCH"
          git pull ${{env.ORIGIN}} $BRANCH
          PULL_CMD_STATUS=$?

          if [ ! $PULL_CMD_STATUS -eq 0 ]
          then
            echo "⛔️ Error detected while pulling from $BRANCH. Aborting."
            exit 1
          fi
          echo ""
        done

        echo "🔥 Pushing to ${{CURRENT_BRANCH}}"
        git push
        PUSH_CMD_STATUS=$?

        if [ ! $PUSH_CMD_STATUS -eq 0 ]
          then
            echo "⛔️ Error detected while pushing to ${{CURRENT_BRANCH}}. Aborting."
            exit 1
          fi
          echo ""
